<?php

namespace GO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DebitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitRepository extends EntityRepository
{
}
