<?php

namespace GO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends EntityRepository
{
}
