<?php

namespace GO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends EntityRepository
{
    public function getCurrentPromo()
    {
        $qb= $this->createQueryBuilder('p');
        $qb->where('p.dateFin >= NOW()');
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
}
