<?php

namespace GO\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemiseCarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseCarteRepository extends EntityRepository
{
    public function hasPromo($carte, $promo)
    {
        $qb=$this->createQueryBuilder('rm');
        $qb->where('rm.carte=:carte')->setParameter('carte', $carte);
        $qb->andWhere('rm.promo=:promo')->setParameter('promo', $promo);
        $qb->andWhere('rm.dateFin >= NOW()');
        $result=$qb->getQuery()->getResult();
        return ($result==null)? false : true;
    }
}
