<?php

namespace GO\SMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Formulerepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormuleRepository extends EntityRepository
{
}
