<?php

namespace GO\SMSBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GO\UserBundle\Entity\User;
use GO\ShopBundle\Utils\Constants as Cons;
/**
 * PayerAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayerAbonnementRepository extends EntityRepository
{
    public function getPaiement(User $user, $condition)
    {
        $qb=$this->createQueryBuilder('p');
        $qb->select('SUM(p.montant) as total');
        switch($condition)
        {
            case Cons::AUJOURDHUI:
       
        $qb->andWhere('MONTH(p.date)=:CURRENT_MO')->setParameter('user', $user);
        }
        switch($condition)
        {
            case Cons::AUJOURDHUI: $qb->where('DATE(p.date)=CURRENT_DATE()');
                 $qb->andWhere('p.user=:user')->setParameter('user', $user);
                break;
            case Cons::MOIS: $qb->where('MONTH(p.date)=MONTH(CURRENT_DATE()) AND YEAR(p.date)=YEAR(CURRENT_DATE())');
                 $qb->andWhere('p.user=:user')->setParameter('user', $user);
                break;
            break;
        }
        return $qb->getQuery()->getSingleScalarResult();
    }
}
