<?php

namespace AppBundle\Repository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll() {
        $exercice=$this->getEntityManager()->getRepository('AppBundle:Exercice')->getCurrent();
      return $this->createQueryBuilder('d')->where('d.exercice=:ex')->setParameter('ex', $exercice)->getQuery()->getResult();
    }
}
