<?php

namespace AppBundle\Repository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrent()
    {
        return $this->createQueryBuilder('e')->where('e.current=:current')->setParameter('current', true)->setMaxResults(1)->getQuery()->getSingleResult();
    }
}
