<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Dossier;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPaiementsDossier(Dossier $dossier)
    {
       return $this->createQueryBuilder('p')->where('p.dossier=:dossier')->setParameter('dossier', $dossier)->getQuery()->getResult();
    }
}
