#jms_security_extra:
   # secure_all_services: false
    #expressions: true
security:
    encoders:
        GO\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUP_CARAV:   [ROLE_AG_CARAV]
        ROLE_AG_BOUT:     [ROLE_AG_CARAV,ROLE_AG_SMS, ROLE_AG_EXPRESS, ROLE_GP]
        ROLE_SUP_BOUT:    [ROLE_AG_BOUT, ROLE_CONS_CLIENT]
        ROLE_CONTROLEUR:  [ROLE_SUP_BOUT,ROLE_SUP_CARAV]
        ROLE_ADMIN:       [ROLE_CONTROLEUR,ROLE_GP,ROLE_CONS_CLIENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_DG, ROLE_DIR_AG]

    providers:
        my_provider:
            id: fos_user.user_provider.username
        

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        fp_js_validator:
            pattern:  ^/fp_js_form_validator
            security: false
        go_login_firewall:
            pattern:  ^/login$
            security: false
        go_test_firewall:
            pattern:  ^/test
            security: false
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api:
            pattern: ^/api                              # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        go_main_firewall:
            pattern:  ^/
            anonymous: false
            provider: my_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: go_main_app_selection
                always_use_default_target_path: true
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            access_denied_handler: go.security.access_denied_handler    
    access_control:
        - { path: ^/shop, roles: ROLE_AG_BOUT}
        - { path: ^/caravane, roles: ROLE_AG_CARAV}
        - { path: ^/admin, roles: ROLE_ADMIN}
        - { path: ^/consulting, roles: ROLE_GP}

