<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreanceProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreanceProduitRepository extends EntityRepository
{
    public function getCreancesNonRemb(Shop $shop, $dateDebut)
    {
        $qb=$this->createQueryBuilder('c');
        $qb->where('c.rembourse=:bool');
        $qb->setParameter('bool', false);
        $qb->andWhere('c.shop=:shop');
        $qb->setParameter('shop', $shop);
        $qb->andWhere('c.dateCreance>=:dateDebut');
        $qb->setParameter('dateDebut', $dateDebut);
        return $qb->getQuery()->getResult();
    }
    public function getTotalCreancesNonRemb(Shop $shop, $dateDebut=null)
    {
        $qb=$this->createQueryBuilder('c');
        $qb->select('SUM(c.quantite*c.prixUnit)')
        ->where('c.rembourse=:bool')
        ->setParameter('bool', false)
        ->andWhere('c.shop=:shop')
        ->setParameter('shop', $shop);
        $qb->andWhere('c.dateCreance>=:dateDebut');
        $qb->setParameter('dateDebut', $dateDebut);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
