<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetteLiquideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetteLiquideRepository extends EntityRepository
{
    public function getTotalDetteNonRemb(Shop $shop,$depuis=null)
    {
        $qb=$this->createQueryBuilder('d');
        $qb->select('SUM(d.montant)')
        ->where('d.rembourse=:bool')
        ->setParameter('bool', false)
        ->andWhere('d.shop=:shop')
        ->setParameter('shop', $shop)
        ->andWhere('d.dateDette>=:dateDepart')
        ->setParameter('dateDepart', $depuis);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
