<?php

namespace GO\ShopBundle\Entity;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Doctrine\ORM\EntityRepository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends EntityRepository
{
    public function getCurrent()
    {
        $exercice=$this->createQueryBuilder('e')->where('e.current=:current')->orderBy("e.id","DESC")->setParameter('current', true)->setMaxResults(1)->getQuery()->getSingleResult();
    
        if(is_null($exercice)|| empty($exercice))
        {
            throw new NotFoundHttpException("Erreur: Aucun exercie en cours trouvé!");
        }
        return $exercice;
        
    }
}
