<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function getListe()
    {
        return $qb= $this->createQueryBuilder('p')->orderBy('p.nom');
                //->where('p.type=1')->orderBy('p.nom');
        
    }
    
    public function getListeProduits()
    {
        $qb= $this->createQueryBuilder('p')
                ->where("p.actif=1")
                ->orderBy('p.categorie,p.nom')
                ->getQuery()
                ->getResult();
        return $qb;
                //->where('p.type=1')->orderBy('p.nom');
        
    }
    public function getHistoriqueVente(Shop $shop,Produit $produit)
    {
        $qb= $this->createQueryBuilder('p')
                ->join('GOShopBundle:Vente', 'v', 'WITH', 'v.produit=p.id')
                ->join('GOShopBundle:Stock', 's', 'WITH', 's.produit=p.id')
                ->addSelect('SUM(v.benefice) as total_benef')
                ->addSelect('SUM(v.quantite*v.prixUnit) as total_vente')
                ->addSelect('v')
                ->addSelect('s');
                
        $qb->where('v.shop=:shop');
        $qb->setParameter('shop', $shop);
        $qb->andWhere('v.produit=:produit');
        $qb->setParameter('produit', $produit);
        return $qb->getQuery()->getResult();
    }
}
