<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReceptionTransfertProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionTransfertProduitRepository extends EntityRepository
{
    public function getPendingReception(Shop $shop, $date=null)
    {
        $qb= $this->createQueryBuilder('rec')
                ->join('rec.transfertProduit','trns')
                ->where('trns.destinataire=:shop')
                ->andWhere('rec.validated=0')
                ->setParameter('shop', $shop);
        return $qb->getQuery()->getResult();
    }
}
