<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RembDetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RembDetteRepository extends EntityRepository
{
}
