<?php

namespace GO\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserShopRepository extends EntityRepository
{
}
