<?php

namespace GO\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GO\UserBundle\Utils\Constants as Cons;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getListeUsers($condition=null)
    {
       $qb=$this->createQueryBuilder('u');
       if($condition==Cons::ACTIVE_USERS)
       {
         $qb->where('u.active= :param') ;
         $qb->setParameter('param', true);
       }
      return $qb->getQuery()->getResult();
      // return $this->findByDepart($id_depart);
                
                
    }
}
