<?php

namespace GO\CaisseBundle\Repository;

/**
 * AbstractSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
