<?php

namespace GO\CaisseBundle\Repository;

/**
 * AbstractEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
