<?php

namespace GO\CaisseBundle\Repository;

/**
 * CaisseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaisseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
