<?php

namespace GO\CaisseBundle\Repository;
use GO\GOLibrary\Utils\DateConstants as DateCons;
use GO\CaisseBundle\Entity\Caisse;
/**
 * CaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoCaisseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListe(Caisse $caisse, $DateCons,$date_debut=null,$date_fin=null)
    {
        $qb= $this->createQueryBuilder('hc');
                $qb->select();
               
        switch($DateCons)
        {
            case DateCons::AUJOURDHUI: $qb->where('DATE(hc.dateOp)=CURRENT_DATE()');
                break;
            case DateCons::MOIS: $qb->where('DATE(hc.dateOp)=MONTH(CURRENT_DATE())');
                break;
            case DateCons::DATE_INTERVALLE: 
                if(!is_null($date_debut))
                {
                    $qb->andWhere('DATE(hc.dateOp)>=:date_debut');
                    $qb->setParameter('date_debut', $date_debut);
                    if(!is_null($date_fin))
                    {
                        $qb->andWhere('DATE(hc.dateOp)<=:date_fin');
                        $qb->setParameter('date_fin', $date_fin);
                    }
                }
                break;
        }
        $qb->andWhere('hc.caisse=:caisse');
         $qb->setParameter('caisse', $caisse);
        return $qb->getQuery()->getResult();
        
    }
}
