<?php

namespace GO\CaisseBundle\Repository;

/**
 * MouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementRepository extends \Doctrine\ORM\EntityRepository
{
}
