<?php

namespace GO\CaisseBundle\Repository;

/**
 * OpBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
