<?php

namespace GO\CaisseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    public function getListe()
    {
        return $qb= $this->createQueryBuilder('s')->where('s.ferme=0');
    }
    public function findAll()
    {
        return $qb= $this->createQueryBuilder('s')->where('s.ferme=0')->getQuery()->getResult();
    }
    public function getOtherShops(Session $session)
    {
      $qb= $this->createQueryBuilder('s')
              ->where('s.id<>:id')
              ->setParameter('id', $session->get('connected_shop')->getId());
              
      return $qb;
    }
}
