<?php

namespace GO\CaisseBundle\Repository;
use GO\CaisseBundle\Entity\Caisse;
use GO\CaisseBundle\Entity\TypeSortie;
use GO\GOLibrary\Utils\DateConstants as Cons;
use Doctrine\ORM\EntityRepository;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends EntityRepository
{
    public function getListeSortie(Caisse $caisse, $condition,$date_debut=null, $date_fin=null)
    {
        $qb= $this->createQueryBuilder('s');
        switch($condition)
        {
            case Cons::AUJOURDHUI: $qb->where('DATE(s.date)=CURRENT_DATE()');
                break;
            case Cons::MOIS: $qb->where('MONTH(s.date)=MONTH(CURRENT_DATE()) AND YEAR(s.date)=YEAR(CURRENT_DATE())');
                break;
            case Cons::DATE_INTERVALLE: 
                if(!is_null($date_debut))
                {
                    $qb->where('DATE(s.date)>=:date_debut');
                    $qb->setParameter('date_debut', $date_debut);
                    if(!is_null($date_fin))
                    {
                        $qb->andWhere('DATE(s.date)<=:date_fin');
                        $qb->setParameter('date_fin', $date_fin);
                    }
                }else
                {
                    throw new \RuntimeException('Aucune date entrée ou format date invalide!');
                }
                break;
        }
         $qb->andWhere('s.caisse=:caisse');
         $qb->setParameter('caisse', $caisse);
         $qb->orderBy('s.date', 'DESC');
       
        return $qb->getQuery()
                ->getResult();
    }
    public function getTotalSortie(Caisse $caisse, $condition,$date_debut=null, $date_fin=null)
    {
        $qb= $this->createQueryBuilder('s')
                ->select('SUM(s.montant)');
         switch($condition)
        {
            case Cons::AUJOURDHUI: $qb->where('DATE(s.date)=CURRENT_DATE()');
                break;
            case Cons::MOIS: $qb->where('MONTH(s.date)=MONTH(CURRENT_DATE()) AND YEAR(s.date)=YEAR(CURRENT_DATE())');
                break;
            case Cons::DATE_INTERVALLE: 
                if(!is_null($date_debut))
                {
                    $qb->where('DATE(s.date)>=:date_debut');
                    $qb->setParameter('date_debut', $date_debut);
                    if(!is_null($date_fin))
                    {
                        $qb->andWhere('DATE(s.date)<=:date_fin');
                        $qb->setParameter('date_fin', $date_fin);
                    }
                }else
                {
                    throw new \RuntimeException('Aucune date entrée ou format date invalide!');
                }
                break;
        }
                $qb->andWhere('s.caisse=:caisse');
                $qb->setParameter('caisse', $caisse);
               return $qb->getQuery()->getSingleScalarResult();
        
    }
    public function getListeTypeSortie(Caisse $caisse,TypeSortie $type, $condition,$date_debut=null, $date_fin=null)
    {
        $qb= $this->createQueryBuilder('s');
        switch($condition)
        {
            case Cons::AUJOURDHUI: $qb->where('DATE(s.date)=CURRENT_DATE()');
                break;
            case Cons::MOIS: $qb->where('MONTH(s.date)=MONTH(CURRENT_DATE()) AND YEAR(s.date)=YEAR(CURRENT_DATE())');
                break;
            case Cons::DATE_INTERVALLE: 
                if(!is_null($date_debut))
                {
                    $qb->where('DATE(s.date)>=:date_debut');
                    $qb->setParameter('date_debut', $date_debut);
                    if(!is_null($date_fin))
                    {
                        $qb->andWhere('DATE(s.date)<=:date_fin');
                        $qb->setParameter('date_fin', $date_fin);
                    }
                }else
                {
                    throw new \RuntimeException('Aucune date entrée ou format date invalide!');
                }
                break;
        }
         $qb->andWhere('s.caisse=:caisse');
         $qb->setParameter('caisse', $caisse);
         $qb->orderBy('s.date', 'DESC');
       
        return $qb->getQuery()
                ->getResult();
    }
    public function getTotalSortieType(Caisse $caisse, TypeSortie $type,$condition,$date_debut=null, $date_fin=null)
    {
        $qb= $this->createQueryBuilder('s')
                ->select('SUM(s.montant)');
         switch($condition)
        {
            case Cons::AUJOURDHUI: $qb->where('DATE(s.date)=CURRENT_DATE()');
                break;
            case Cons::MOIS: $qb->where('MONTH(s.date)=MONTH(CURRENT_DATE()) AND YEAR(s.date)=YEAR(CURRENT_DATE())');
                break;
            case Cons::DATE_INTERVALLE: 
                if(!is_null($date_debut))
                {
                    $qb->where('DATE(s.date)>=:date_debut');
                    $qb->setParameter('date_debut', $date_debut);
                    if(!is_null($date_fin))
                    {
                        $qb->andWhere('DATE(s.date)<=:date_fin');
                        $qb->setParameter('date_fin', $date_fin);
                    }
                }else
                {
                    throw new \RuntimeException('Aucune date entrée ou format date invalide!');
                }
                break;
        }
                $qb->andWhere('s.caisse=:caisse')->setParameter('caisse', $caisse);
                 $qb->andWhere('s.type=:type')->setParameter('type', $type);
               return $qb->getQuery()->getSingleScalarResult();
        
    }
}
