<?php

namespace GO\CaisseBundle\Repository;

/**
 * TypeSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
