<?php

namespace GO\CaisseBundle\Repository;

/**
 * TypeEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
