parameters:
#    go_caravane.example.class: GO\CaravaneBundle\Example

services:
    gocar.custom_validator:
        class: GO\CaravaneBundle\Utils\CustomValidator
    go_main.twig_extension:
        class: GO\MainBundle\Twig\GOMainTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    go_user.form.registration:
        class: GO\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: go_user_registration }
    go_caravane.type.tel_to_client_transformer:
        class: GO\CaravaneBundle\Form\TelephoneToClientTransformerType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: carav_tel_to_client_transformer }

