<?php

namespace GO\CaravaneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BilanDepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilanDepartRepository extends EntityRepository
{
}
