<?php

namespace GO\CaravaneBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GO\CaravaneBundle\Utils\Constants as Cons;

/**
 * DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findOneByTel($tel)
    {
        return $qb= $this->createQueryBuilder('c')
                ->join("c.coordonnees", "cc")
               ->addSelect( "cc")
               ->where('SUBSTRING(cc.tel,-9,9)=:tel')
               ->setParameter('tel', $tel)
                ->getQuery()->getOneOrNullResult();
                            
    }
}
