parameters:
#    go_express.example.class: GO\ExpressBundle\Example

services:
#    go_express.example:
#        class: %go_express.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
