<?php

namespace GO\ClientBundle\Repository;

/**
 * AbstractCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
