<?php

namespace GO\ClientBundle\Repository;

/**
 * CompteClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteClientRepository extends \Doctrine\ORM\EntityRepository
{
}
